import { useState, useEffect, useRef, useMemo, useCallback } from "react";
import { C, FD, FB, FM, FONTS, THEMES, FONT_SIZES, api, uid, showT, playNotifSound, exportCSV, exportTableCSV, nameColor, t, LANGS, now, ROUTES, AUDIT_LOG, CUSTOM_FIELDS_INIT, EMAIL_SIGS_INIT, BRANDS_INIT, A0, L0, IB0, TM0, CR0, AU0, CT0, CV0, MG0, AI_S, BOT, REPLY_POOL, SDLogo, ChIcon, chI, chC, prC, NavIcon, Av, Tag, Btn, Inp, Sel, CompanyPicker, Toggle, Mdl, CountUp, Confetti, ConvPreview, Fld, Spin, Skel, SkelRow, SkelCards, SkelMsgs, SkelTable, EmptyState, ErrorBanner, ConnBadge, AiInsight, LoadingOverlay, UndoToast, OnboardingWizard, CsatSurvey, SlaTimer, CollisionBadge, CfPanel, CfInput, Sparkline, DonutChart, LazyMount, NotifPanel } from "../shared";

// ─── BILLING ──────────────────────────────────────────────────────────────
// ─── KNOWLEDGE BASE ───────────────────────────────────────────────────────
const KB_CATS=[{id:"kc1",name:"Getting Started",icon:"🚀",desc:"Setup guides and onboarding"},{id:"kc2",name:"Account & Billing",icon:"💳",desc:"Plans, payments, and invoices"},{id:"kc3",name:"Channels",icon:"📱",desc:"WhatsApp, Email, SMS, and more"},{id:"kc4",name:"Inbox & Conversations",icon:"💬",desc:"Managing and resolving tickets"},{id:"kc5",name:"Contacts & CRM",icon:"👥",desc:"Contact management and segmentation"},{id:"kc6",name:"AI & Automation",icon:"🤖",desc:"AI copilot, bots, and workflows"},{id:"kc7",name:"Reports & Analytics",icon:"📊",desc:"Dashboards, metrics, and exports"},{id:"kc8",name:"Integrations",icon:"🔗",desc:"Connecting third-party tools"},{id:"kc9",name:"Marketing",icon:"📣",desc:"Campaigns, A/B tests, and segments"},{id:"kc10",name:"Troubleshooting",icon:"🔧",desc:"Fixing common issues"}];
const KB_ARTICLES=[
  // Getting Started
  {id:"ka1",cat:"kc1",title:"Quick Start Guide",tags:["setup","onboarding"],status:"published",views:2840,helpful:94,updated:"08/04/26",body:"Welcome to SupportDesk! This guide walks you through the essential setup steps to get your support platform running.\n\n1. CREATE YOUR FIRST INBOX\nGo to Settings > Inboxes > + New Inbox. Choose your channel type (Live Chat, Email, WhatsApp, etc.), enter a name, and configure your greeting message. For channels like WhatsApp and Email, you will need to provide API credentials in the Connection tab.\n\n2. INVITE YOUR TEAM\nGo to Settings > Agents & Teams > Invite Agent. Enter their email, choose a role (Agent or Admin), and send the invitation. Agents can then set their availability and notification preferences.\n\n3. CONFIGURE AI BOT\nGo to Settings > AI Bot to enable Claude-powered auto-replies. Toggle on channels where you want AI assistance, set response tone, and configure fallback behavior.\n\n4. INSTALL THE WIDGET\nGo to Widget Builder to customize your chat widget appearance, then copy the embed code from the Install tab and paste it into your website HTML.\n\n5. CONNECT INTEGRATIONS\nVisit the Integration Marketplace to connect tools like Slack, Jira, Shopify, and 30+ more apps."},
  {id:"ka2",cat:"kc1",title:"Setting Up Your First Inbox",tags:["inbox","channels","setup"],status:"published",views:1890,helpful:91,updated:"08/04/26",body:"Inboxes are the core of SupportDesk. Each inbox represents a channel where conversations arrive.\n\nCREATING AN INBOX\n1. Navigate to Settings > Inboxes\n2. Click + New Inbox\n3. Fill in the General tab: Name, Channel Type, Greeting Message, Widget Color\n4. For external channels (WhatsApp, Email, SMS), go to the Connection tab and enter your credentials\n5. Configure Business Hours, Assignment rules, SLA targets, and Notifications in their respective tabs\n\nCHANNEL TYPES AVAILABLE\nLive Chat — Website widget for real-time messaging\nEmail — IMAP/SMTP for email support\nWhatsApp — WhatsApp Business API\nTelegram — Bot token integration\nFacebook — Page messaging\nInstagram — DM integration\nSMS — Twilio-powered texting\nVoice — Phone call support\nVideo — Video call support\nAnd more: Viber, LINE, TikTok, X, Apple Business Chat, API\n\nEach inbox can have its own SLA targets, business hours, auto-assignment rules, and notification preferences."},
  {id:"ka3",cat:"kc1",title:"Inviting & Managing Team Members",tags:["agents","teams","roles"],status:"published",views:1420,helpful:93,updated:"08/04/26",body:"Your support team is managed under Settings > Agents & Teams.\n\nINVITING AGENTS\n1. Click Invite Agent\n2. Enter Full Name and Email\n3. Choose Role: Agent (handle conversations) or Admin (manage settings + agents)\n4. The agent receives an email invitation and can set up their profile\n\nEDITING AGENTS\nClick the edit button on any agent to access 4 tabs:\n- Profile: Name, email, role, status, max concurrent conversations\n- Permissions: Toggle access to Conversations, Contacts, Reports, Marketing, Integrations, Settings, Billing\n- Availability: Working hours, timezone, auto-away settings\n- Performance: Resolved count, avg reply time, CSAT, recent activity\n\nCREATING TEAMS\nTeams group agents for routing. Create teams with:\n- Members: Select agents to include\n- Auto-Assignment: Round Robin, Load Balanced, or Manual Queue\n- Schedule: Set team-specific working hours and days\n\nROLES & PERMISSIONS\nThe Roles tab shows a full 18-permission matrix for Owner, Admin, and Agent roles."},
  {id:"ka4",cat:"kc1",title:"Understanding the Dashboard",tags:["home","dashboard","overview"],status:"published",views:1680,helpful:89,updated:"08/04/26",body:"The Home dashboard provides a real-time overview of your support operations.\n\nKPI CARDS (top row)\n- Open Conversations: Active tickets needing attention\n- Urgent/High Priority: Conversations requiring immediate response\n- Unassigned: Conversations without an assigned agent\n- Resolved Today: Tickets closed today\n- CSAT Score: Customer satisfaction for the last 7 days\n\nACTIVITY FEED\nReal-time stream of events: new messages, SLA warnings, AI auto-replies, label changes, resolved conversations. Click any item to jump directly to that conversation.\n\nQUICK ACTIONS\nOne-click shortcuts: New Conversation, View All Open, Contacts, Live Visitors, Reports, AI Bot Settings.\n\nCHANNEL ACTIVITY\nBar chart showing conversation volume per channel, ranked by volume.\n\nAGENT STATUS\nLive availability of all agents with online/offline indicators and workload."},
  {id:"ka5",cat:"kc1",title:"Keyboard Shortcuts",tags:["shortcuts","productivity"],status:"published",views:920,helpful:96,updated:"08/04/26",body:"SupportDesk supports keyboard shortcuts for faster navigation.\n\nGLOBAL SHORTCUTS\nCtrl+K / Cmd+K — Open Command Palette (search screens, actions, settings)\nCtrl+1 — Jump to Inbox\nCtrl+2 — Jump to Contacts\nCtrl+3 — Jump to Reports\nEsc — Close any modal or palette\n\nINBOX SHORTCUTS\nEnter — Send message\nShift+Enter — New line in compose\n\nCOMMAND PALETTE\nType to search across all screens, navigate to any page, toggle dark mode, export data, and more."},
  // Account & Billing
  {id:"ka6",cat:"kc2",title:"Managing Your Subscription",tags:["billing","plans","upgrade"],status:"published",views:1050,helpful:87,updated:"08/04/26",body:"Manage your plan at the Billing screen.\n\nPLANS\nStarter (Free): 5 agents, 3 inboxes, Live Chat + Email, basic reports, 7-day history\nPro (4,999/mo): 25 agents, 10 inboxes, all channels, AI Copilot, advanced reports, automations, 90-day history\nEnterprise (Custom): Unlimited agents/inboxes, SSO/SAML, SLA management, audit logs, dedicated support\n\nUPGRADING\nClick Upgrade on any plan card. Review the payment summary (including GST), then confirm. Changes apply immediately.\n\nUSAGE METERS\nTrack your consumption: Agents used, Inboxes created, Conversations this month, AI Credits used. Each shows a progress bar against your plan limit."},
  {id:"ka7",cat:"kc2",title:"Payment Methods & Invoices",tags:["billing","invoices","payment"],status:"published",views:780,helpful:85,updated:"08/04/26",body:"INVOICES\nView all past invoices in Billing > Recent Invoices. Each shows the plan, month, invoice number, amount, and payment status. Click the PDF button to download.\n\nPAYMENT METHODS\nAdd credit/debit cards or UPI for automatic billing. Enterprise customers can pay via bank transfer with NET-30 terms.\n\nTAX\nAll Indian invoices include 18% GST. International customers are tax-exempt."},
  // Channels
  {id:"ka8",cat:"kc3",title:"WhatsApp Business Setup",tags:["whatsapp","channels","api"],status:"published",views:2560,helpful:95,updated:"08/04/26",body:"Connect your WhatsApp Business account to SupportDesk.\n\nPREREQUISITES\n- WhatsApp Business API account (via Meta Business)\n- Verified business phone number\n- Facebook Business Manager access\n\nSETUP STEPS\n1. Go to Settings > Inboxes > + New Inbox\n2. Select WhatsApp as channel type\n3. Go to Connection tab\n4. Enter: Phone Number, WhatsApp Business API Key, Webhook Callback URL\n5. Click Test Connection to verify\n6. Configure greeting message, business hours, SLA in other tabs\n\nFEATURES\n- Receive and reply to WhatsApp messages\n- Send template messages (pre-approved by Meta)\n- Rich media support: images, documents, location\n- Read receipts and delivery status\n- AI auto-reply support\n\nMARKETING\nUse Marketing > WhatsApp tab to send bulk campaigns with template messages."},
  {id:"ka9",cat:"kc3",title:"Email Channel (IMAP/SMTP)",tags:["email","channels","imap","smtp"],status:"published",views:1980,helpful:90,updated:"08/04/26",body:"Set up email support with any email provider.\n\nSETUP\n1. Create inbox with Email channel type\n2. Connection tab requires: IMAP Host, IMAP Port (993), SMTP Host, SMTP Port (587), Email Address, Password/App Password\n\nGMAIL SETUP\nIMMP Host: imap.gmail.com, Port: 993\nSMTP Host: smtp.gmail.com, Port: 587\nUse an App Password (not your Google password) — generate one at myaccount.google.com/apppasswords\n\nOUTLOOK/OFFICE 365\nIMAP: outlook.office365.com:993\nSMTP: smtp.office365.com:587\n\nCUSTOM DOMAIN\nUse your mail server IMAP/SMTP settings. Ensure TLS/SSL is enabled.\n\nFEATURES\n- Threading: replies are grouped into conversations\n- Attachments: files are preserved\n- HTML rendering: rich email formatting supported\n- Auto-routing: assign by sender domain, subject keywords"},
  {id:"ka10",cat:"kc3",title:"Facebook & Instagram DMs",tags:["facebook","instagram","social","channels"],status:"published",views:1420,helpful:88,updated:"08/04/26",body:"Connect Facebook Page Messenger and Instagram Direct Messages.\n\nFACEBOOK SETUP\n1. Create inbox with Facebook channel\n2. Enter Page ID and Page Access Token\n3. Access Token requires: pages_messaging, pages_read_engagement permissions\n\nINSTAGRAM SETUP\n1. Create inbox with Instagram channel\n2. Enter Business Account ID and Access Token\n3. Requires Instagram Professional account linked to a Facebook Page\n\nFEATURES\n- Reply to DMs from SupportDesk\n- See customer profile info\n- Image and media support\n- Story reply notifications\n- AI auto-reply works on both channels"},
  {id:"ka11",cat:"kc3",title:"Telegram Bot Setup",tags:["telegram","bot","channels"],status:"published",views:820,helpful:87,updated:"08/04/26",body:"Connect a Telegram bot to receive and respond to messages.\n\n1. Create a bot via BotFather on Telegram (send /newbot)\n2. Copy the Bot Token\n3. Create inbox with Telegram channel\n4. Enter Bot Token and Webhook URL\n5. Telegram will send all messages to your webhook\n\nSupported: text, images, documents, location sharing."},
  {id:"ka12",cat:"kc3",title:"SMS via Twilio",tags:["sms","twilio","channels"],status:"published",views:680,helpful:84,updated:"08/04/26",body:"Send and receive SMS using Twilio.\n\nSETUP\n1. Create a Twilio account at twilio.com\n2. Get your Account SID, Auth Token, and a Twilio phone number\n3. Create inbox with SMS channel\n4. Enter credentials in Connection tab\n\nFEATURES\n- Two-way SMS conversations\n- MMS support (images, media)\n- Delivery receipts\n- Marketing campaigns via Marketing > SMS tab\n- Character counting (160 per segment)"},
  {id:"ka13",cat:"kc3",title:"Voice & Video Calls",tags:["voice","video","calls","channels"],status:"published",views:540,helpful:82,updated:"08/04/26",body:"Enable voice and video calling in your widget.\n\nVOICE SETUP\n1. Create inbox with Voice channel\n2. Connect Twilio credentials (SID, Auth Token, Phone Number)\n3. Enable Voice in Widget Builder > General tab\n\nVIDEO SETUP\n1. Create inbox with Video channel\n2. Enter Video API Key\n3. Enable Video in Widget Builder\n\nWIDGET\nCustomers see phone and video icons on the chat widget. Clicking initiates a call with real-time audio/video."},
  // Inbox & Conversations
  {id:"ka14",cat:"kc4",title:"Conversation Lifecycle",tags:["conversations","status","workflow"],status:"published",views:1860,helpful:92,updated:"08/04/26",body:"Every conversation follows a lifecycle:\n\nOPEN — New or active conversation needing a response\nASSIGNED — An agent is handling it\nSNOOZED — Temporarily paused (1h, 2h, 4h, 8h, 24h, 3 days)\nRESOLVED — Issue is closed\n\nACTIONS\n- Resolve: Close the conversation (Ctrl+Enter on resolved button)\n- Reopen: Resume a resolved conversation\n- Snooze: Pause and auto-reopen after duration\n- Transfer: Move to another team\n- Assign: Assign to specific agent\n- Set Priority: Urgent, High, Normal\n- Add Labels: Tag with custom labels\n\nBULK ACTIONS\nEnable bulk mode in the inbox list. Select multiple conversations, then Resolve, Assign, or Label all at once."},
  {id:"ka15",cat:"kc4",title:"AI Copilot & Auto-Reply",tags:["ai","copilot","auto-reply","claude"],status:"published",views:2240,helpful:96,updated:"08/04/26",body:"SupportDesk includes a Claude-powered AI copilot.\n\nAI DRAFT\nClick AI Draft in the compose bar. Claude analyzes the conversation context and generates 3 reply suggestions. Click any suggestion to load it into the compose box.\n\nAI AUTO-REPLY\nToggle AI Auto-Reply ON in the chat header. Claude will automatically respond to every customer message using conversation context, customer info, and your canned responses.\n\nAI SUMMARIZE\nClick Summarize to get an AI-generated summary of the entire conversation including key issues, resolution status, sentiment, and topic tags.\n\nAI CLASSIFY + LABEL\nClick Classify to have AI analyze the conversation and automatically apply relevant labels and adjust priority based on content.\n\nSETTINGS\nConfigure AI behavior in Settings > AI Bot:\n- Enable/disable per channel\n- Set response tone (Professional, Friendly, Concise)\n- Configure knowledge sources\n- Test the bot with a live chat interface"},
  {id:"ka16",cat:"kc4",title:"Internal Notes & Collaboration",tags:["notes","collaboration","team"],status:"published",views:980,helpful:90,updated:"08/04/26",body:"Collaborate with your team using internal notes.\n\nSENDING NOTES\nToggle Reply/Note in the compose toolbar. Notes appear as yellow-tinted bubbles with a INTERNAL NOTE header.\n\nNotes are visible only to agents — customers never see them. Notes do not trigger auto-replies.\n\nMESSAGE ACTIONS\nHover any message to see the action bar:\n- Reply: Set as reply-to (shows quoted context)\n- Copy: Copy text to clipboard\n- Edit: Modify your own messages (shows edited indicator)\n- Delete: Remove your own messages\n- Forward: Load text into compose with FWD prefix"},
  {id:"ka17",cat:"kc4",title:"Canned Responses",tags:["canned","macros","shortcuts"],status:"published",views:1340,helpful:91,updated:"08/04/26",body:"Save time with pre-written replies.\n\nCREATING\nGo to Settings > Canned Responses > + New Response\nSet a shortcode (e.g. greet) and the full response text.\nUse {{name}} for dynamic variables.\n\nUSING IN CHAT\nClick /canned in the compose toolbar, or type / in the message box.\nSearch by shortcode or content. Click to insert.\n\nEXAMPLES\n/greet — Hi {{name}}! Welcome to SupportDesk. How can I help?\n/refund — I have initiated your refund. It will reflect in 5-7 business days.\n/escalate — I am escalating this to our specialist team who will contact you shortly."},
  {id:"ka18",cat:"kc4",title:"Message Search & Filters",tags:["search","filters","inbox"],status:"published",views:760,helpful:86,updated:"08/04/26",body:"Find conversations and messages quickly.\n\nCONVERSATION FILTERS\n- Status: Open, Resolved, Snoozed, All\n- Owner: All, Mine, Unassigned\n- Channel: All, Live, Email, WhatsApp, Facebook, Instagram, SMS\n- Search bar: Search by contact name or subject\n\nSAVED VIEWS\nPre-configured filter combinations: My VIP Tickets, Unresolved WhatsApp, All Urgent. Click to apply instantly.\n\nMESSAGE SEARCH\nClick the search icon in the chat header. Type to search within the current conversation. Matching messages are highlighted with a yellow outline. Shows match count."},
  // Contacts & CRM
  {id:"ka19",cat:"kc5",title:"Managing Contacts",tags:["contacts","crm","customers"],status:"published",views:1560,helpful:89,updated:"08/04/26",body:"The Contacts screen manages all your customers.\n\nCONTACT FIELDS\nName, Email, Phone, Company, Plan, Tags, CSAT Score, Total Conversations, Notes\n\nACTIONS\n- Create: + New Contact button\n- Edit: Click any contact to open detail panel\n- Delete: Remove contacts\n- Search: By name, email, or company\n- Filter: By plan, tags\n\nDETAIL PANEL\nClick a contact to see full profile, conversation history, notes, and tags in the right panel."},
  {id:"ka20",cat:"kc5",title:"Contact Segmentation",tags:["segments","targeting","crm"],status:"published",views:890,helpful:87,updated:"08/04/26",body:"Segment contacts for targeted actions.\n\nPRE-BUILT SEGMENTS (Marketing > Segments tab)\n- All Contacts (5,200)\n- Active Customers (3,100)\n- Inactive 30d+ (1,400)\n- High Value VIP (420)\n- New Signups 7d (180)\n- Cart Abandoners (640)\n- Newsletter Subs (8,900)\n- Pro/Enterprise (320)\n- Churned Risk (280)\n- Champions (150)\n\nSEGMENT BUILDER\nCreate custom segments with filter rules:\nAttribute (Status, Plan, Activity, Spend, Channel, Tags, Location, Language)\nOperator (equals, not equals, contains, greater than, less than)\nValue\nAdd multiple rules with AND logic. See estimated reach in real-time.\n\nUse segments in marketing campaigns for targeted messaging."},
  // AI & Automation
  {id:"ka21",cat:"kc6",title:"AI Bot Configuration",tags:["ai","bot","settings","claude"],status:"published",views:1980,helpful:95,updated:"08/04/26",body:"Configure the AI bot in Settings > AI Bot.\n\nCHANNEL TOGGLES\nEnable/disable AI on each channel independently. Grouped by: Chat (Live, Email, WhatsApp, Telegram), Social (Facebook, Instagram, TikTok, X), Messaging (Viber, Apple, LINE), Other (SMS, Voice, Video, API).\n\nRESPONSE TONE\nSet the AI personality: Professional, Friendly, Concise, Technical.\n\nKNOWLEDGE SOURCES\nThe AI uses conversation history, customer context, canned responses, and (soon) Knowledge Base articles to generate replies.\n\nTEST CHAT\nUse the built-in test chat to interact with your AI bot and verify behavior before going live."},
  {id:"ka22",cat:"kc6",title:"Automation Rules",tags:["automations","rules","workflows"],status:"published",views:1420,helpful:90,updated:"08/04/26",body:"Automate repetitive tasks with rules.\n\nSettings > Automations lets you create trigger-based rules:\n\nCOMPONENTS\n- Trigger: The event that starts the automation (New Conversation, Message Contains, Priority Changed, SLA Breach, Contact Created)\n- Conditions: Optional filters (channel equals, label includes, priority is)\n- Actions: What happens (Assign Agent, Add Label, Set Priority, Send Message, Notify Agent, Transfer Team)\n\nEXAMPLES\n- Auto-assign: When channel = WhatsApp AND priority = urgent, assign to Agent A\n- Auto-label: When message contains refund, add label billing\n- SLA alert: When SLA breach, notify team lead\n\nMARKETING AUTOMATIONS\nVisit Marketing > Automations for multi-step campaign workflows: Welcome Series, Cart Recovery, Post-Purchase Review, Re-engagement, Birthday Offer, Payment Reminder."},
  {id:"ka23",cat:"kc6",title:"AI Studio — Marketing Tools",tags:["ai","marketing","studio"],status:"published",views:1120,helpful:93,updated:"08/04/26",body:"The AI Studio (Marketing > AI Studio) provides 4 Claude-powered marketing tools:\n\n1. SUBJECT LINE GENERATOR\nEnter a topic and tone. AI generates 5 subject line variants. Copy any variant or run an A/B test with the top 2.\n\n2. COPY WRITER\nProvide a brief, select channel and tone. AI writes full campaign copy with CTA, personalization variables, and channel-appropriate formatting.\n\n3. SMART TIMING\nDescribe your audience. AI recommends optimal send times for Email, WhatsApp, and SMS with reasoning for each.\n\n4. PERFORMANCE ADVISOR\nPaste your campaign metrics. AI analyzes and provides 4 specific optimization recommendations with industry benchmarks."},
  // Reports & Analytics
  {id:"ka24",cat:"kc7",title:"Reports Overview",tags:["reports","analytics","dashboard"],status:"published",views:1680,helpful:91,updated:"08/04/26",body:"The Reports screen has 6 tabs covering all analytics.\n\nOVERVIEW\n4 KPI cards (Total Conversations, Resolved, Avg First Reply, CSAT) with sparkline trends. Volume bar chart, Resolution Funnel, Response Time distribution, Status Breakdown donut, Top Labels.\n\nCONVERSATIONS\n5 metric cards, volume trend chart, resolution funnel, and a Busiest Hours Heatmap (7 days x 24 hours).\n\nAGENTS\nFull leaderboard table: Rank (medals), Agent, Resolved, Avg Reply, CSAT, Load, Conversations, Performance Score.\n\nCHANNELS\nPerformance table per channel with SVG brand icons, volume comparison horizontal bars.\n\nSLA\n4 compliance gauges (semicircle SVG arcs), compliance trend bar chart.\n\nCSAT\nOverall CSAT, Total Ratings, NPS Score, Rating Distribution (5-star bars), CSAT by Agent.\n\nAll tabs support period selection: 7D, 30D, 90D, 1Y. Export as CSV."},
  {id:"ka25",cat:"kc7",title:"Exporting Data",tags:["export","csv","data"],status:"published",views:640,helpful:83,updated:"08/04/26",body:"Export data from multiple locations:\n\nREPORTS\nClick Export in the Reports header to download current view as CSV.\n\nCOMMAND PALETTE\nPress Ctrl+K, type Export — downloads all conversations as CSV with ID, Subject, Status, Channel, Agent, Priority columns.\n\nCHAT TRANSCRIPTS\nIn any conversation, click More Options (three dots) > Export Chat to copy the full transcript to clipboard.\n\nINVOICES\nDownload PDF invoices from Billing > Recent Invoices."},
  // Integrations
  {id:"ka26",cat:"kc8",title:"Integration Marketplace",tags:["integrations","marketplace","apps"],status:"published",views:1890,helpful:92,updated:"08/04/26",body:"The Marketplace (Integrations > Marketplace) offers 32+ integrations.\n\nBROWSING\n- Featured section: Top recommended apps\n- New Arrivals: Recently added integrations\n- Browse by Category: Communication, CRM, E-commerce, Payments, Automation, Productivity, Marketing, Analytics, Development, AI, Custom\n- Search: Find by name, category, or description\n\nAPP DETAIL\nClick any app to see: description, required permissions, credentials needed, rating, install count, and rating breakdown.\n\nCONNECTING\n1. Click Install & Connect\n2. Enter required credentials\n3. Click Test & Connect\n4. Configure sync settings\n\nCONFIGURING\nConnected apps show a Configure button with 3 tabs: Settings (sync toggles), Activity (sync logs), Danger (disconnect)."},
  {id:"ka27",cat:"kc8",title:"API Keys & Webhooks",tags:["api","webhooks","developers"],status:"published",views:1340,helpful:89,updated:"08/04/26",body:"API KEYS (Integrations > API Keys)\n- Create keys with name and permissions (read, write, webhook, admin)\n- Keys shown once after generation — save securely\n- Usage tracking with progress bars\n- Revoke/Activate toggle per key\n- Code examples: curl, Node.js, Python\n\nWEBHOOKS (Integrations > Webhooks)\n- Create webhooks with endpoint URL and event subscriptions\n- Events: conversation.created/resolved/reopened/assigned, message.created/updated, contact.created/updated/deleted, agent.status_changed/assigned\n- Webhook signing secret for verification\n- Logs: View delivery history, success rates, replay events, send test deliveries\n- Pause/Resume/Delete per webhook\n\nAPI DOCS\nFull REST API documentation in Integrations > Docs with 9 sections covering authentication, endpoints, webhooks, errors, and rate limits."},
  {id:"ka28",cat:"kc8",title:"Slack Integration",tags:["slack","notifications","integrations"],status:"published",views:1560,helpful:94,updated:"08/04/26",body:"Connect Slack for bi-directional support.\n\nSETUP\n1. Find Slack in the Marketplace\n2. Click Install & Connect\n3. Enter Workspace URL, Bot Token, Default Channel\n4. Test connection\n\nFEATURES\n- New conversation notifications in Slack channels\n- Reply to customers directly from Slack threads\n- Escalate Slack threads to SupportDesk conversations\n- Assignment and resolution notifications\n- Configurable sync settings"},
  {id:"ka29",cat:"kc8",title:"Shopify & E-commerce",tags:["shopify","woocommerce","ecommerce","integrations"],status:"published",views:1120,helpful:88,updated:"08/04/26",body:"Connect your e-commerce store for customer context.\n\nSHOPIFY\n- Enter Shop Domain and Admin API Token\n- View customer orders in conversation sidebar\n- Process refunds directly from conversations\n- Auto-tag VIP customers based on order value\n\nWOOCOMMERCE\n- Enter Store URL, Consumer Key, Consumer Secret\n- Same features as Shopify integration\n\nBoth integrations sync customer data, order history, and product information into the conversation view."},
  // Marketing
  {id:"ka30",cat:"kc9",title:"Creating Marketing Campaigns",tags:["campaigns","marketing","messaging"],status:"published",views:1780,helpful:93,updated:"08/04/26",body:"The Marketing screen has 10 tabs for comprehensive campaign management.\n\nCREATING A CAMPAIGN\n1. Click + New Campaign\n2. Step 1 — Details: Channel (WhatsApp/Email/SMS/Push), name, goal (Promotion/Engagement/Retention), status, A/B test toggle\n3. Step 2 — Content: Choose template or write custom content. Insert variables ({first_name}, {discount}, etc.). Use AI Generate for Claude-written copy. Live preview per channel.\n4. Step 3 — Audience: Select segment (7 pre-built + custom), see estimated reach\n5. Step 4 — Review: Full summary table + message preview. Save Draft or Launch.\n\nPER-CHANNEL BUTTONS\nQuick-create: + WA, + Email, + SMS, + Push — opens wizard pre-set to that channel.\n\nCAMPAIGN DETAIL\nClick any campaign to see 5-tab detail: Overview (8 KPIs + funnel + sparkline), Content (preview + send test), Audience (breakdown), A/B Results (variant comparison), Settings (metadata + export + delete)."},
  {id:"ka31",cat:"kc9",title:"A/B Testing Campaigns",tags:["ab-test","testing","optimization"],status:"published",views:1240,helpful:91,updated:"08/04/26",body:"Run A/B tests to optimize campaign performance.\n\nCREATING AN A/B TEST\n1. Click A/B Test in the Marketing header\n2. Step 1 — Setup: Name, channel, primary metric (Open Rate/CTR/Conversion/Revenue), duration (6h-72h), winner selection (Auto/Manual/Statistical)\n3. Step 2 — Variants: Write Variant A (Control) and Variant B (Challenger). Use AI Generate for each — A gets formal tone, B gets casual tone. Side-by-side preview.\n4. Step 3 — Audience: Select segment + drag split slider (10%-90%)\n5. Step 4 — Review: Full summary + variant comparison + info box explaining post-test behavior\n\nRESULTS\nA/B campaigns show an A/B badge in the list. Open detail > A/B Results tab to see performance comparison and declare a winner."},
  {id:"ka32",cat:"kc9",title:"Marketing Templates",tags:["templates","content","marketing"],status:"published",views:980,helpful:88,updated:"08/04/26",body:"21 ready-to-use templates across 4 channels.\n\nBROWSING\nMarketing > Templates tab. Filter by channel (Email/WhatsApp/SMS/Push) and category (Onboarding/Promotion/Retention/Engagement/Billing/Transactional).\n\nEach template shows: channel icon, name, description, category tag, avg open rate, avg CTR.\n\nUSING\nClick Preview to see the template with variables filled in. Click Use to load it into the campaign wizard.\n\nEXAMPLES\n- Welcome Series #1 (Email, 58% open, 22% CTR)\n- Flash Sale (WhatsApp, 78% open, 35% CTR)\n- Payment Due (SMS, 88% open, 25% CTR)\n- Deal Alert (Push, 45% open, 18% CTR)"},
  // Troubleshooting
  {id:"ka33",cat:"kc10",title:"Channel Connection Issues",tags:["troubleshooting","connection","errors"],status:"published",views:1560,helpful:80,updated:"08/04/26",body:"Common connection problems and solutions.\n\nWHATSAPP NOT CONNECTING\n- Verify API key is from WhatsApp Business API (not personal)\n- Check webhook URL is publicly accessible (not localhost)\n- Ensure phone number includes country code\n\nEMAIL NOT RECEIVING\n- Verify IMAP host and port (993 for SSL)\n- For Gmail, enable Less Secure Apps or use App Password\n- Check firewall allows IMAP connections\n\nTELEGRAM BOT NOT RESPONDING\n- Verify bot token from BotFather\n- Ensure no other service is using the same webhook URL\n- Check bot is not blocked by the user\n\nFACEBOOK/INSTAGRAM\n- Page Access Token may have expired — regenerate in Facebook Developer Console\n- Verify page_messaging permission is granted\n\nGENERAL\n- Use the Test Connection button in inbox settings\n- Check API Logs (Integrations > API Logs) for error details"},
  {id:"ka34",cat:"kc10",title:"AI Bot Not Responding",tags:["ai","troubleshooting","bot"],status:"published",views:1120,helpful:78,updated:"08/04/26",body:"If the AI bot is not generating replies:\n\n1. CHECK CHANNEL TOGGLE\nSettings > AI Bot — ensure the channel is toggled ON\n\n2. CHECK AUTO-REPLY MODE\nIn the inbox chat header, ensure AI Auto-Reply is toggled ON\n\n3. API AVAILABILITY\nThe AI uses the Anthropic API. If the API is temporarily unavailable, fallback responses will be used.\n\n4. RATE LIMITS\nAI has usage limits based on your plan. Check Billing > Usage to see AI Credits consumed.\n\n5. CONTEXT ISSUES\nAI needs conversation context. Very short or ambiguous messages may not generate good replies. The AI improves with more conversation history."},
  {id:"ka35",cat:"kc10",title:"Widget Not Appearing",tags:["widget","troubleshooting","embed"],status:"published",views:890,helpful:75,updated:"08/04/26",body:"If the chat widget is not showing on your website:\n\n1. CHECK EMBED CODE\nWidget Builder > Install tab — ensure the script tag is placed before the closing </body> tag\n\n2. CHANNEL ENABLED\nWidget Builder > General tab — at least one channel (Chat, Voice, or Video) must be enabled\n\n3. BUSINESS HOURS\nIf business hours are set on the inbox, the widget may be hidden outside those hours\n\n4. BROWSER CACHE\nClear your browser cache and hard-refresh (Ctrl+Shift+R)\n\n5. CONSOLE ERRORS\nCheck browser Developer Tools (F12) > Console for any JavaScript errors"},
  {id:"ka36",cat:"kc10",title:"SLA Breach Notifications",tags:["sla","notifications","alerts"],status:"published",views:680,helpful:82,updated:"08/04/26",body:"Understanding SLA breaches:\n\nSLA targets are set per inbox (Settings > Inboxes > Configure > SLA tab):\n- First Reply Target: Time to first agent response\n- Resolution Target: Time to resolve the conversation\n\nWHEN SLA IS BREACHED\n- Conversation gets a visual SLA warning indicator\n- Notification sent to assigned agent and team lead\n- Shows in Reports > SLA tab with compliance percentages\n\nPREVENTING BREACHES\n- Enable auto-assignment for faster first response\n- Use AI Auto-Reply for instant acknowledgment\n- Set up automation: When SLA breach imminent, escalate priority and notify"},
  // Extra comprehensive articles
  {id:"ka37",cat:"kc4",title:"Emoji, Formatting & Attachments",tags:["compose","formatting","emoji","attachments"],status:"published",views:720,helpful:88,updated:"08/04/26",body:"Rich messaging features in the compose toolbar:\n\nFORMATTING\n- Bold: Click B or wrap text in **bold**\n- Italic: Click I or wrap in _italic_\n- Strikethrough: Click ~ or wrap in ~~text~~\n\nEMOJI PICKER\nClick the smile icon to open 30 frequently-used emojis. Click any to insert.\n\nATTACHMENTS\nClick the paperclip icon to attach files. Supports images, documents, PDFs up to the configured max size (set in inbox Advanced settings).\n\nREAD RECEIPTS\nAgent messages show checkmarks: single tick (sent), double tick (read by customer)."},
  {id:"ka38",cat:"kc7",title:"Live Visitor Monitoring",tags:["monitor","visitors","live"],status:"published",views:940,helpful:85,updated:"08/04/26",body:"The Live Monitor screen shows real-time visitor activity.\n\n3 TABS:\n- List: All active visitors with name, location, current page, duration, device type. Click Invite or Start Chat.\n- Map: Geographic distribution of visitors (placeholder for real map integration)\n- Analytics: Visitor stats (total, desktop/mobile split, avg duration)\n\nACTIONS\n- Invite to Chat: Send a proactive chat invitation to a browsing visitor\n- Start Chat: Immediately open a conversation with a visitor\n\nVISITOR DATA\nSee which page visitors are on, how long they have been browsing, their device type, and referral source."},
  {id:"ka39",cat:"kc1",title:"Theme & Appearance Customization",tags:["theme","fonts","appearance","customization"],status:"published",views:1280,helpful:92,updated:"08/04/26",body:"Customize the look and feel of SupportDesk.\n\nTHEMES (Settings > Theme)\n8 color themes with live preview: Midnight, Ocean, Forest, Sunset, Lavender, Rose, Monochrome, Clean. Each shows a mini app mockup. Click to apply instantly.\n\nFONTS (Settings > Fonts)\nText Size: 5 presets from Extra Small (82%) to Extra Large (120%) with visual slider and live preview.\nFont Pairs: 8 font combinations (Syne+DM Sans, Inter, Space Grotesk, Outfit, Plus Jakarta, Manrope, Bricolage, Satoshi). Hover to preview, click to apply.\n\nDARK/LIGHT TOGGLE\nClick the sun/moon icon in the URL bar to instantly switch between dark and light modes."},
  {id:"ka40",cat:"kc6",title:"Marketing Automations",tags:["automations","marketing","workflows"],status:"published",views:860,helpful:89,updated:"08/04/26",body:"Pre-built marketing automation flows (Marketing > Automations tab):\n\n6 AUTOMATIONS:\n1. Welcome Series (Email): Contact Created > Send welcome > Wait 2d > Tips > Wait 3d > Offer\n2. Cart Recovery (WhatsApp): Cart Abandoned > Wait 1h > WA reminder > Wait 24h > Discount email\n3. Post-Purchase Review: Order Delivered > Wait 3d > Feedback WA > Wait 5d > NPS email\n4. Re-engagement (Email): Inactive 30d > Miss-you email > Wait 7d > SMS offer > Wait 14d > Mark churned\n5. Birthday Offer (WhatsApp): Birthday match > Send WA greeting > Apply 20% coupon\n6. Payment Reminder (SMS): Due date > SMS 3d before > Email 1d before > SMS on due date\n\nEach shows: trigger, step chain, enrolled/completed counts, and ON/OFF toggle."},
  {id:"ka41",cat:"kc8",title:"Jira & Project Management",tags:["jira","asana","linear","project-management"],status:"published",views:780,helpful:86,updated:"08/04/26",body:"Connect project management tools for developer escalation.\n\nJIRA\n- Enter Domain, Email, API Token, Project Key\n- Create Jira issues directly from conversations\n- Auto-sync status: when Jira issue is resolved, conversation gets notified\n- Attach conversation context to issues\n\nLINEAR\n- Enter API Key and Team ID\n- Same bi-directional sync as Jira\n- Modern issue tracking integration\n\nASANA\n- Enter Personal Access Token and Workspace ID\n- Create tasks from conversations\n- Track task completion\n\nMONDAY.COM\n- Enter API Token and Board ID\n- Create items from conversations"},
  {id:"ka42",cat:"kc5",title:"CSAT & Customer Feedback",tags:["csat","feedback","satisfaction"],status:"published",views:1060,helpful:90,updated:"08/04/26",body:"Track customer satisfaction across all channels.\n\nCSAT SURVEYS\nAfter resolving a conversation, a 2-step survey automatically appears to the customer: Step 1 is an emoji rating (1-5 stars from Terrible to Excellent), Step 2 is an optional comment box. Scores are stored on the conversation and visible in Reports.\n\nCSAT TRENDS\nThe Home dashboard includes a CSAT Trends widget showing daily average ratings as a bar chart for the last 7 days, with weekly trend comparison.\n\nREPORTS\nReports > CSAT tab shows overall score, response rate, NPS, rating distribution, and CSAT by Agent with progress bars.\n\nAI INSIGHTS\nThe AI Report Insights feature analyzes CSAT trends and flags agents or channels with declining satisfaction scores."},
  {id:"ka43",cat:"kc5",title:"CRM — Deals Pipeline",tags:["crm","deals","pipeline","kanban"],status:"published",views:1840,helpful:93,updated:"08/04/26",body:"Manage your sales pipeline in the CRM module.\n\nACCESSING CRM\nClick CRM in the left navigation. The module has 4 tabs: Leads, Deals, Tasks, Meetings.\n\nDEALS PIPELINE\nThe Deals tab shows a drag-and-drop kanban board with 6 stages: Lead, Qualified, Proposal, Negotiation, Won, Lost. Each deal card shows company, value, probability, owner, and close date.\n\nCREATING DEALS\nClick + New Deal. Fill in: Deal Name, Company, Contact, Value, Stage, Probability (0-100%), Owner, Close Date, Source, and Notes.\n\nDEAL DETAIL\nClick any deal to open the detail sidebar with 3 tabs:\n- Details: All fields, stage progress bar, edit/delete\n- Activity: Timeline of calls, emails, meetings, notes with timestamps\n- Notes: Internal notes with Enter-to-save\n\nCUSTOM FIELDS\nDeals support custom fields: Contract Length, Discount %, Competitor (multi-select), Decision Date, Champion. Configure in Settings > Custom Fields > Deals.\n\nAI ADVISOR\nClick Refresh on the CRM AI Advisor panel for deal risk alerts, lead prioritization, and next-best-action recommendations with specific names and dollar amounts.\n\nCSV EXPORT\nClick Export to download all deals as CSV."},
  {id:"ka44",cat:"kc5",title:"CRM — Lead Management",tags:["crm","leads","scoring","conversion"],status:"published",views:1520,helpful:91,updated:"08/04/26",body:"Track and convert leads in the CRM.\n\nLEAD STAGES\nNew, Contacted, Qualified, Nurturing, Converted, Lost. Leads flow through these stages as you engage with prospects.\n\nLEAD SCORING\nEach lead has a score (0-100) based on engagement signals. Higher scores indicate more sales-ready leads. The AI Auto-Tag feature automatically classifies new conversations and can boost lead scores.\n\nCREATING LEADS\nClick + New Lead. Fields: Name, Email, Phone, Company, Source (Website, LinkedIn, Referral, etc.), Owner, Estimated Value.\n\nCONVERSION\nFrom the lead detail sidebar, click Convert to Contact to create a contact record, or Create Deal to move the lead into the deals pipeline.\n\nCUSTOM FIELDS\nLeads support: Lead Source Detail, Intent Score, First Touch channel. Configure in Settings > Custom Fields > Leads.\n\nBULK OPERATIONS\nSelect multiple leads for bulk stage change, assignment, or export."},
  {id:"ka45",cat:"kc5",title:"CRM — Tasks & Meetings",tags:["crm","tasks","meetings","scheduling"],status:"published",views:1180,helpful:89,updated:"08/04/26",body:"Track follow-ups and schedule meetings.\n\nTASKS\nCreate tasks with: Title, Assignee, Status (To Do, In Progress, Done), Priority (Urgent, High, Normal, Low), Due Date, Description. Tasks can be linked to deals, leads, or contacts.\n\nMEETINGS\nSchedule meetings with: Title, Contact, Company, Date, Time, Duration, Host, Type (Call, Video, In-Person), Status (Scheduled, Completed, Cancelled, No-Show), Location, Notes, Agenda.\n\nCUSTOM FIELDS\nTasks support Estimated Hours and Billable checkbox. Meetings support Meeting Link and Recording URL. Configure in Settings > Custom Fields.\n\nCSV EXPORT\nBoth tasks and meetings have Export buttons for CSV download."},
  {id:"ka46",cat:"kc4",title:"Team Chat — Channels & DMs",tags:["chat","team","channels","messaging"],status:"published",views:1690,helpful:94,updated:"08/04/26",body:"Communicate with your team using the built-in Team Chat.\n\nCHANNELS\nPublic channels for topic-based discussion: #general, #support-escalations, #engineering, #sales, #random. Create new channels with + New Channel button.\n\nDIRECT MESSAGES\nPrivate 1-on-1 conversations between team members.\n\nMULTI-PANE LAYOUT\nOpen up to 3 chat panes simultaneously (1 main + 2 secondary) — similar to Zoho Cliq. Right-click any channel or DM to open in a secondary pane.\n\nFEATURES\n- Threads: Reply to specific messages in a thread sidebar\n- Reactions: 16 emoji reactions on any message (hover > react)\n- Pins: Pin important messages for quick reference\n- File sharing: Share documents, images, PDFs\n- Message editing and deletion\n- Search with text highlighting\n- Typing indicators\n\nSLASH COMMANDS (12)\n/help, /status, /clear, /poll, /remind, /assign, /note, /link, /giphy, /translate, /summarize, /standup\n\nAI FEATURES\n- Channel Summarize: AI summary of recent messages\n- Smart Reply Suggestions: AI-generated response options\n- Standup Report Generator: AI creates daily standup from channel activity"},
  {id:"ka47",cat:"kc5",title:"Custom Fields — 8 Entities × 16 Types",tags:["custom-fields","configuration","data"],status:"published",views:1340,helpful:92,updated:"08/04/26",body:"Extend SupportDesk with custom data fields across all entities.\n\n8 SUPPORTED ENTITIES\nContact, Conversation, Deal, Lead, Company, Task, Meeting, Booking. Each entity has its own field configuration.\n\n16 FIELD TYPES\nText, Long Text, Number, Currency, Percentage, Date, Dropdown (single-select), Multi-Select, Checkbox, URL, Email, Phone, Rating (1-5 stars), File Upload, Color Picker, Agent Picker.\n\nCONFIGURATION\nSettings > Custom Fields. Click any entity tab to see its fields organized by groups (Account, Billing, Classification, etc.).\n\nFIELD OPTIONS\n- Required / Optional\n- Unique constraint\n- Min/Max validation (for numbers)\n- Regex pattern validation (for text, e.g. BUG-1234 format)\n- Conditional visibility (show field only when another field matches a value)\n- Placeholder text and default values\n\nWHERE FIELDS APPEAR\nCustom fields render in 8 detail panels across the app:\n1. Inbox > Conversation detail tab\n2. Inbox > Contact detail tab\n3. Contacts > Detail sidebar\n4. CRM > Deal detail\n5. CRM > Lead detail\n6. CRM > Task detail\n7. CRM > Meeting detail\n8. Companies > Detail panel\n\nAI SUGGESTIONS\nClick AI Suggest to have Claude analyze your existing fields and recommend 5 new ones with one-click add.\n\nEXPORT\nExport field definitions as JSON for backup or migration."},
  {id:"ka48",cat:"kc6",title:"AI Sales Agent — Multi-Agent System",tags:["ai","sales","agent","playbooks"],status:"published",views:2180,helpful:96,updated:"08/04/26",body:"Create specialized AI sales agents powered by Claude.\n\nAGENT LIST\nSettings > AI Sales Agent shows all agents as cards with metrics: Leads qualified, Demos booked, Deals created, Revenue, Conversion rate.\n\n3 PRE-BUILT AGENTS\n- Aria (Inbound Sales): Live Chat + WhatsApp + Facebook, consultative tone\n- Max (Enterprise Closer): Live Chat + Email, challenger tone\n- Zara (WhatsApp & Social): WhatsApp + Instagram + Facebook, friendly tone\n\nCREATING AGENTS\nClick + New Agent. Configure: Name, Role, Avatar (16 emojis), Color (8 options), Sales Tone (Consultative, Friendly, Professional, Challenger, Solution Selling), Language, Channel toggles.\n\n7 CONFIG TABS PER AGENT\n1. Overview: 4 KPIs + activity feed + performance metrics\n2. Playbooks: 5 pre-built sales playbooks with step editor\n3. Qualification: 6 scoring rules with thresholds, auto-qualify/CRM/demo toggles\n4. Objections: 6 objection handlers with win rates and CRUD\n5. Products: 3-tier pricing matrix with AI qualifier rules\n6. Config: Name, tone, language, channels, system prompt, handoff threshold, max turns\n7. Test: Multi-turn Claude conversations with message history\n\nACTIONS\nCreate, Edit, Delete, Duplicate, Toggle Active/Paused for each agent."},
  {id:"ka49",cat:"kc7",title:"Live Visitor Monitoring & World Map",tags:["monitor","visitors","map","real-time"],status:"published",views:1450,helpful:91,updated:"08/04/26",body:"Track website visitors in real-time.\n\n3 TABS\n1. Visitor List: Table showing name, current page, location, device, time on site, status (browsing/active/chatting), with invite and chat actions\n2. World Map: SVG geographic map with 24 regions showing visitor dots with glow effects, connection lines between chatters, glassmorphism panels, LIVE indicator\n3. Analytics: KPIs (Online Now, Chatting, Avg Session, Bounce Risk), Top Pages, Top Countries, Device breakdown, Referral sources\n\nPROACTIVE CHAT\nClick Invite on any visitor to send a proactive chat invitation with a custom message. Click Start Chat to immediately open a conversation.\n\nAI VISITOR INTENT\nClick Refresh on the Visitor Intent Prediction panel. AI classifies each visitor as: likely buyer, support seeker, competitor research, or casual browser — with specific proactive chat triggers.\n\nFILTERS\nFilter visitors by: All, Chatting, Invited. Search by name."},
  {id:"ka50",cat:"kc5",title:"Calendar & Scheduling",tags:["calendar","events","scheduling"],status:"published",views:1120,helpful:88,updated:"08/04/26",body:"Manage your team calendar and events.\n\n3 VIEWS\n- Month: Grid calendar with event dots\n- Week: 7-day column layout with time slots\n- Day: Detailed hourly timeline\n\nEVENT TYPES\nMeeting, Task Due, Call, Demo, Deadline, Follow-up, Internal, Personal. Each type has a unique icon and color.\n\nCREATING EVENTS\nClick + New Event or click any date on the calendar. Fill in: Title, Date, Start/End Time, Type, Description.\n\nAI SMART SCHEDULING\nClick Refresh on the Smart Scheduling panel for:\n- Optimal meeting slots (no conflicts)\n- Overloaded day warnings\n- Prep reminders for upcoming demos\n- Missing follow-up detection\n- Buffer time recommendations"},
  {id:"ka51",cat:"kc5",title:"Booking Pages & Appointments",tags:["bookings","appointments","scheduling"],status:"published",views:980,helpful:87,updated:"08/04/26",body:"Create scheduling links for customers to book meetings.\n\nBOOKING PAGES\n3 pre-built pages: 30-min Strategy Call, 15-min Quick Chat, 60-min Product Demo. Create more with + New Booking Page.\n\nPAGE SETTINGS\nName, Duration, Color, Description, Active/Paused toggle.\n\nKPI DASHBOARD\nActive Pages, Total Bookings, Upcoming, Completed, No-Shows — all with color-coded counters.\n\nBOOKING MANAGEMENT\n- Upcoming tab: Confirmed bookings with confirm/cancel/reschedule actions\n- Past tab: Completed, cancelled, and no-show bookings\n- Settings tab: Default duration, buffer time, availability\n\nAI BOOKING INTELLIGENCE\nClick Refresh for no-show prediction, optimal time slot analysis, follow-up suggestions, and booking pattern insights.\n\nCSV EXPORT\nExport all bookings as CSV."},
  {id:"ka52",cat:"kc9",title:"Campaign Validators — 30 Rules",tags:["marketing","validators","whatsapp","email","sms"],status:"published",views:1680,helpful:95,updated:"08/04/26",body:"Real-time validation for marketing campaigns across all channels.\n\nWHATSAPP VALIDATORS (7 rules)\n- Max 4,096 characters (error)\n- Over 1,024 chars truncation warning\n- No HTML tags allowed (error)\n- Missing personalization variables warning\n- Too many links (>3) warning\n- Template approval required for broadcast warning\n- Missing opt-out text — STOP/unsubscribe required (error)\n\nEMAIL VALIDATORS (11 rules)\n- Subject line required (error)\n- Subject > 150 chars (error), > 60 chars mobile truncation warning\n- ALL CAPS subject warning, multiple !!! warning\n- Spam word detector: 12 trigger words (free, winner, urgent, act now, etc.)\n- Missing personalization warning (+29% open rate with {{first_name}})\n- Missing unsubscribe link (error)\n- Body too short warning, missing CTA link warning, too many links (>5)\n\nSMS VALIDATORS (8 rules)\n- Over 480 chars / 3 segments (error with cost estimate)\n- Multi-segment cost calculation ($X for Y contacts)\n- Unicode detection (70 chars/segment vs 160)\n- Missing STOP opt-out (error)\n- No personalization warning, raw URL warning, >50% CAPS warning\n\nPUSH VALIDATORS (2 rules)\n- Over 240 chars truncation warning\n- Optimal length reminder (40-100 chars)\n\nUI INTEGRATION\nValidation runs live in Step 2 (Content). Errors block Step 2→3. Step 4 (Review) shows summary banner: green (all passed), yellow (warnings), red (errors). Launch button disabled on errors. Confirm dialog on warnings. Drafts always saveable."},
  {id:"ka53",cat:"kc9",title:"Marketing A/B Testing",tags:["marketing","ab-testing","optimization"],status:"published",views:1240,helpful:90,updated:"08/04/26",body:"Test campaign variations to optimize performance.\n\nCREATING A/B TESTS\nClick A/B Test in the Marketing module. Choose channel, set test name, select metric (Open Rate, Click Rate, Conversion, Revenue), duration (6h to 7 days), and winner selection (auto/manual).\n\nVARIANTS\nCreate Variant A and Variant B with different:\n- Subject lines (email)\n- Message content\n- Send times\n- CTAs\n\nRESULTS\nAfter the test period, view side-by-side comparison with statistical significance indicator. The winning variant can be automatically sent to the remaining audience.\n\nAI ANALYSIS\nUse the A/B Analyzer in AI Studio to get AI-powered analysis of test results with recommendations for future campaigns."},
  {id:"ka54",cat:"kc6",title:"Bot Builder — Visual Flow Editor",tags:["bot","builder","flow","no-code"],status:"published",views:1560,helpful:93,updated:"08/04/26",body:"Build custom chatbot flows without coding.\n\nACCESSING\nSettings > Bot Builder opens the visual flow editor.\n\nNODE TYPES\n- Trigger: Start of flow (visitor opens chat, keyword match, page visit)\n- Message: Send a text message to the visitor\n- Question: Ask for input (text, email, phone, select, date)\n- Condition: Branch based on answer (if/else)\n- Action: Assign agent, add tag, create contact, set priority\n- AI: Let Claude generate a response based on context\n- Transfer: Hand off to human agent\n- End: Close the flow\n\nBUILDING FLOWS\n1. Drag nodes from the palette onto the canvas\n2. Connect nodes by dragging from output to input\n3. Configure each node (double-click to edit)\n4. Test the flow with the Preview button\n5. Publish to make it live\n\nTEMPLATES\n3 pre-built templates: Lead Qualifier, FAQ Bot, Appointment Scheduler."},
  {id:"ka55",cat:"kc4",title:"Conversation Snooze & Merge",tags:["snooze","merge","inbox","productivity"],status:"published",views:890,helpful:88,updated:"08/04/26",body:"Advanced conversation management features.\n\nSNOOZE\nClick the Snooze button in the conversation toolbar. Choose duration: 1 hour, 2 hours, 4 hours, 8 hours, 24 hours, or 3 days. The conversation moves to Snoozed status and automatically reopens when the timer expires. A system message logs the snooze event.\n\nMERGE\nClick Merge in the conversation actions. Select a target conversation from the dropdown. All messages from the current conversation are moved to the target with a [Merged] prefix. The source conversation is deleted. Useful for duplicate tickets from the same customer.\n\nCONTACT MERGE\nIn Contacts, select two contacts and click Merge. Tags, notes, and conversation counts are combined. The secondary contact is removed."},
  {id:"ka56",cat:"kc5",title:"Bulk CSV Import & Export",tags:["import","export","csv","contacts"],status:"published",views:1020,helpful:86,updated:"08/04/26",body:"Import and export data in bulk.\n\nIMPORTING CONTACTS\n1. In Contacts, click Import CSV\n2. Select your CSV file (must have header row + data rows)\n3. Auto-mapping detects columns: name, email, phone, company, plan, notes, location, timezone, language\n4. Review and adjust column mappings\n5. Preview first 3 rows\n6. Click Import — contacts are created with auto-generated avatars and colors\n\nEXPORTING DATA\nCSV Export buttons are available on:\n- Contacts (name, email, phone, company, plan)\n- CRM Leads, Deals, Tasks, Meetings (all fields)\n- Reports (trend data by period)\n- KB Articles (title, category, status, views)\n- Bookings (name, email, date, time, status)\n\nCOMMAND PALETTE EXPORT\nPress Ctrl+K, type export to quickly export current conversations as CSV."},
  {id:"ka57",cat:"kc1",title:"Notification Preferences & Quiet Hours",tags:["notifications","preferences","quiet-hours","dnd"],status:"published",views:760,helpful:84,updated:"08/04/26",body:"Control when and how you receive notifications.\n\nNOTIFICATION MATRIX\nSettings > Notifications shows a grid of 6 events × 4 channels:\n\nEvents: New Message, Assignment, SLA Breach, Mentions, Conversation Resolved, New Contact\nChannels: In-App, Email, Push, Slack\n\nToggle each combination on/off independently.\n\nDO NOT DISTURB\nToggle DND to pause ALL notifications. A red banner reminds you when DND is active.\n\nQUIET HOURS\nEnable Quiet Hours and set From/Until times (e.g., 10:00 PM to 8:00 AM). Notifications are suppressed during this window.\n\nREAL-TIME ALERTS\nWebSocket pushes 4 event types: chat_message, conversation_update, sla_breach, new_conversation. Sound alerts play for new conversations (configurable)."},
  {id:"ka58",cat:"kc6",title:"Automations & Workflows",tags:["automations","workflows","rules","triggers"],status:"published",views:1380,helpful:91,updated:"08/04/26",body:"Automate repetitive tasks with rules and workflows.\n\nAUTOMATION RULES\nSettings > Automations. Each rule has:\n- Trigger: Conversation created, Message received, Status changed, SLA approaching\n- Conditions: Channel equals, Priority equals, Labels contain, Contact plan equals\n- Actions: Assign agent, Add label, Set priority, Send canned response, Notify Slack, Move to team\n\nEXAMPLES\n- Auto-assign WhatsApp to Support team\n- Add Urgent label when subject contains payment or down\n- Send greeting canned response on first message\n- Notify #escalations Slack channel on SLA breach\n\nWORKFLOWS\nSettings > Workflows provides multi-step automation chains with conditional branching. Create visual flows that combine multiple triggers, conditions, and actions.\n\nAI AUTO-TAG\nNew conversations are automatically classified by AI into Bug, Billing, Feature Request, Onboarding, Urgent, or General — and the appropriate label is applied instantly."}
];

export default function KnowledgeBaseScr(){
  const [kbTab,setKbTab]=useState("articles");
  const [articles,setArticles]=useState(KB_ARTICLES);
  const [kbSearch,setKbSearch]=useState("");
  const [kbCatFilter,setKbCatFilter]=useState("all");
  const [kbStatusFilter,setKbStatusFilter]=useState("all");
  const [showEditor,setShowEditor]=useState(false);
  const [editArt,setEditArt]=useState(null);
  const [artTitle,setArtTitle]=useState("");
  const [artBody,setArtBody]=useState("");
  const [artCat,setArtCat]=useState("kc1");
  const [artStatus,setArtStatus]=useState("draft");
  const [artTags,setArtTags]=useState("");
  const [viewArt,setViewArt]=useState(null);
  const [aiGenLoad,setAiGenLoad]=useState(false);
  const [contentLang,setContentLang]=useState("en");
  // ═══ KB API LOADING ═══
  useEffect(()=>{if(!api.isConnected())return;api.get("/kb/articles").then(r=>{if(r?.articles?.length)setArticles(r.articles.map(a=>({...a,cat:a.category_id||"kc1",tags:a.slug?[a.slug]:[],helpful:a.helpful_count||0,views:a.views||0,updated:a.updated_at?.split("T")[0]||""})));}).catch(()=>{});},[]);

  const filtered=articles.filter(a=>{
    if(kbCatFilter!=="all"&&a.cat!==kbCatFilter)return false;
    if(kbStatusFilter!=="all"&&a.status!==kbStatusFilter)return false;
    if(kbSearch&&!a.title.toLowerCase().includes(kbSearch.toLowerCase())&&!a.body.toLowerCase().includes(kbSearch.toLowerCase())&&!(a.tags||[]).some(t=>t.includes(kbSearch.toLowerCase())))return false;
    return true;
  });
  const saveArt=()=>{
    if(!artTitle.trim())return showT("Title required","error");
    const tags=artTags.split(",").map(t=>t.trim()).filter(Boolean);
    if(editArt)setArticles(p=>p.map(a=>a.id===editArt.id?{...a,title:artTitle,body:artBody,cat:artCat,status:artStatus,tags,updated:new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"2-digit",year:"2-digit"})}:a));
    else setArticles(p=>[{id:"ka"+uid(),title:artTitle,body:artBody,cat:artCat,status:artStatus,tags,views:0,helpful:0,updated:new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"2-digit",year:"2-digit"})},...p]);
    showT(editArt?"Article updated":"Article created!","success");setShowEditor(false);setEditArt(null);
  };
  const genAIArticle=async()=>{
    if(!artTitle.trim())return showT("Enter a title first","error");
    setAiGenLoad(true);
    try{const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:800,system:"You are a technical writer creating help center articles for a customer support SaaS platform called SupportDesk. Write clear, structured content with section headers in ALL CAPS, numbered steps, and practical examples. No markdown formatting.",messages:[{role:"user",content:"Write a comprehensive knowledge base article titled: "+artTitle+". Cover setup steps, features, best practices, and troubleshooting tips."}]})});
      const data=await res.json();setArtBody(data.content?.[0]?.text||"Unable to generate. Try again.");
    }catch(e){setArtBody("AI service unavailable. Please write the article manually.");}
    setAiGenLoad(false);
  };
  const relatedArticles=viewArt?articles.filter(a=>a.id!==viewArt.id&&(a.cat===viewArt.cat||(a.tags||[]).some(t=>(viewArt.tags||[]).includes(t)))).slice(0,4):[];

  return <div style={{flex:1,display:"flex",flexDirection:"column",minWidth:0}}>
    <div style={{padding:"14px 24px",borderBottom:`1px solid ${C.b1}`,background:C.s1,display:"flex",alignItems:"center",gap:14}}>
      {viewArt?<>
        <button onClick={()=>setViewArt(null)} style={{background:C.s3,border:`1px solid ${C.b1}`,borderRadius:7,padding:"5px 12px",fontSize:12,color:C.t2,cursor:"pointer",fontFamily:FB}}>← Back</button>
        <h2 style={{fontSize:18,fontWeight:800,fontFamily:FD,flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{viewArt.title}</h2>
        <Btn ch="✎ Edit" v="ghost" sm onClick={()=>{setEditArt(viewArt);setArtTitle(viewArt.title);setArtBody(viewArt.body);setArtCat(viewArt.cat);setArtStatus(viewArt.status);setArtTags((viewArt.tags||[]).join(", "));setViewArt(null);setShowEditor(true);}}/>
      </>:<>
        <h2 style={{fontSize:20,fontWeight:800,fontFamily:FD}}>Knowledge Base</h2>
        <div style={{flex:1}}/>
        <div style={{display:"flex",alignItems:"center",gap:6,background:C.bg,border:`1px solid ${C.b1}`,borderRadius:8,padding:"5px 10px",maxWidth:300}}>
          <span style={{color:C.t3,fontSize:12}}>⌕</span>
          <input value={kbSearch} onChange={e=>setKbSearch(e.target.value)} placeholder="Search articles, tags, content…" style={{flex:1,background:"none",border:"none",fontSize:12,color:C.t1,fontFamily:FB,outline:"none"}}/>
          {kbSearch&&<button onClick={()=>setKbSearch("")} style={{color:C.t3,background:"none",border:"none",cursor:"pointer",fontSize:12}}>×</button>}
        </div>
        <select value={contentLang||"en"} onChange={e=>{const v=e.target.value;if(typeof setContentLang==="function")setContentLang(v);showT("Content language: "+(v==="en"?"English":v==="hi"?"Hindi":"Spanish"),"info");}} style={{background:C.s3,border:`1px solid ${C.b1}`,borderRadius:6,color:C.t2,fontSize:10,padding:"4px 6px",cursor:"pointer",fontFamily:FM,outline:"none"}} aria-label="Content language">
          <option value="en">EN</option><option value="hi">HI</option><option value="es">ES</option>
        </select>
        <Btn ch="↓ Export" v="ghost" sm onClick={()=>{exportTableCSV(["Title","Category","Status","Views","Helpful %","Updated"],articles.map(a=>[a.title,a.cat,a.status,a.views,a.helpful+"%",a.updated]),"kb_articles.csv");showT("Exported "+articles.length+" articles","success");}}/>
        <Btn ch="↓ Export" v="ghost" sm onClick={()=>{exportTableCSV(["Title","Category","Status","Views","Helpful %","Updated"],articles.map(a=>[a.title,a.cat,a.status,a.views,a.helpful+"%",a.updated]),"kb_articles.csv");showT("Exported "+articles.length+" articles","success");}}/>
        <Btn ch="+ New Article" v="primary" onClick={()=>{setEditArt(null);setArtTitle("");setArtBody("");setArtCat("kc1");setArtStatus("draft");setArtTags("");setShowEditor(true);}}/>
      </>}
    </div>
    {!viewArt&&<div style={{display:"flex",borderBottom:`1px solid ${C.b1}`,background:C.s1,padding:"0 24px"}}>
      {[["articles","Articles","knowledgebase"],["categories","Categories","widget"],["analytics","Analytics","reports"]].map(([id,lbl,navId])=>(
        <button key={id} onClick={()=>setKbTab(id)} style={{padding:"11px 16px",fontSize:10.5,fontWeight:700,fontFamily:FM,color:kbTab===id?C.a:C.t3,borderBottom:`2px solid ${kbTab===id?C.a:"transparent"}`,background:"transparent",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:5}}><NavIcon id={navId} s={13} col={kbTab===id?C.a:C.t3}/>{lbl}</button>
      ))}
    </div>}
    <div style={{flex:1,overflowY:"auto",padding:"20px 24px"}}>

      {/* ═══ ARTICLE READER VIEW ═══ */}
      {viewArt?<div style={{maxWidth:760}}>
        <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}>
          <Tag text={viewArt.status} color={viewArt.status==="published"?C.g:C.y}/>
          <span style={{fontSize:11,color:C.t3,fontFamily:FM}}>{KB_CATS.find(c=>c.id===viewArt.cat)?.icon} {KB_CATS.find(c=>c.id===viewArt.cat)?.name}</span>
          <span style={{fontSize:11,color:C.t3,fontFamily:FM}}>· Updated {viewArt.updated}</span>
          <span style={{fontSize:11,color:C.t3,fontFamily:FM}}>· {viewArt.views} views</span>
        </div>
        <h1 style={{fontSize:26,fontWeight:800,fontFamily:FD,marginBottom:12,lineHeight:1.3}}>{viewArt.title}</h1>
        {(viewArt.tags||[]).length>0&&<div style={{display:"flex",gap:4,marginBottom:18,flexWrap:"wrap"}}>
          {viewArt.tags.map(tag=><span key={tag} style={{padding:"3px 10px",borderRadius:14,fontSize:10,fontFamily:FM,color:C.cy,background:C.cy+"15",border:`1px solid ${C.cy}33`}}>#{tag}</span>)}
        </div>}
        {/* Article body rendered with section formatting */}
        <div style={{fontSize:14,color:C.t2,lineHeight:1.8}}>
          {viewArt.body.split("\n").map((line,i)=>{
            if(!line.trim())return <div key={i} style={{height:10}}/>;
            if(line===line.toUpperCase()&&line.length>3&&line.length<60)return <h3 key={i} style={{fontSize:15,fontWeight:700,color:C.t1,fontFamily:FD,marginTop:18,marginBottom:6}}>{line}</h3>;
            if(/^\d+\./.test(line.trim()))return <div key={i} style={{paddingLeft:12,marginBottom:4,display:"flex",gap:8}}><span style={{color:C.a,fontWeight:700,fontFamily:FM,flexShrink:0}}>{line.trim().match(/^\d+/)[0]}.</span><span>{line.trim().replace(/^\d+\.\s*/,"")}</span></div>;
            if(line.trim().startsWith("- "))return <div key={i} style={{paddingLeft:12,marginBottom:4,display:"flex",gap:8}}><span style={{color:C.a}}>•</span><span>{line.trim().slice(2)}</span></div>;
            return <p key={i} style={{marginBottom:6}}>{line}</p>;
          })}
        </div>
        {/* Helpful feedback */}
        <div style={{marginTop:28,padding:"18px",background:C.s1,border:`1px solid ${C.b1}`,borderRadius:14,textAlign:"center"}}>
          <div style={{fontSize:13,fontWeight:600,marginBottom:10}}>Was this article helpful?</div>
          <div style={{display:"flex",justifyContent:"center",gap:10}}>
            <button onClick={()=>{setArticles(p=>p.map(a=>a.id===viewArt.id?{...a,helpful:Math.min(a.helpful+1,100)}:a));showT("Thanks for the feedback!","success");}} style={{padding:"8px 24px",borderRadius:8,fontSize:12,fontWeight:600,cursor:"pointer",background:C.gd,color:C.g,border:`1px solid ${C.g}44`}}>👍 Yes</button>
            <button onClick={()=>showT("Thanks! We will improve this article.","info")} style={{padding:"8px 24px",borderRadius:8,fontSize:12,fontWeight:600,cursor:"pointer",background:C.rd,color:C.r,border:`1px solid ${C.r}44`}}>👎 No</button>
          </div>
          <div style={{fontSize:11,color:C.t3,marginTop:8}}>{viewArt.helpful}% of readers found this helpful</div>
        </div>
        {/* Related articles */}
        {relatedArticles.length>0&&<div style={{marginTop:24}}>
          <div style={{fontSize:14,fontWeight:700,fontFamily:FD,marginBottom:12}}>Related Articles</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
            {relatedArticles.map(ra=>(
              <button key={ra.id} onClick={()=>{setViewArt(ra);setArticles(p=>p.map(a=>a.id===ra.id?{...a,views:a.views+1}:a));}} className="hov" style={{padding:"12px 14px",borderRadius:10,background:C.s1,border:`1px solid ${C.b1}`,cursor:"pointer",textAlign:"left",transition:"background .12s"}}>
                <div style={{fontSize:12.5,fontWeight:600,color:C.t1,marginBottom:3}}>{ra.title}</div>
                <div style={{fontSize:10,color:C.t3,fontFamily:FM}}>{KB_CATS.find(c=>c.id===ra.cat)?.icon} {KB_CATS.find(c=>c.id===ra.cat)?.name} · {ra.views} views</div>
              </button>
            ))}
          </div>
        </div>}
      </div>:<>

      {/* ═══ ARTICLES LIST ═══ */}
      {kbTab==="articles"&&<>
        <div style={{display:"flex",gap:4,marginBottom:14,flexWrap:"wrap"}}>
          <button onClick={()=>setKbCatFilter("all")} style={{padding:"4px 10px",borderRadius:20,fontSize:10,fontWeight:700,fontFamily:FM,cursor:"pointer",background:kbCatFilter==="all"?C.ad:"transparent",color:kbCatFilter==="all"?C.a:C.t3,border:`1px solid ${kbCatFilter==="all"?C.a+"50":C.b1}`}}>All ({articles.length})</button>
          {KB_CATS.map(cat=>{const cnt=articles.filter(a=>a.cat===cat.id).length;return(
            <button key={cat.id} onClick={()=>setKbCatFilter(cat.id)} style={{padding:"4px 10px",borderRadius:20,fontSize:10,fontWeight:700,fontFamily:FM,cursor:"pointer",background:kbCatFilter===cat.id?C.ad:"transparent",color:kbCatFilter===cat.id?C.a:C.t3,border:`1px solid ${kbCatFilter===cat.id?C.a+"50":C.b1}`}}>{cat.icon} {cat.name} ({cnt})</button>
          );})}
          <div style={{flex:1}}/>
          {["all","published","draft"].map(s=>(
            <button key={s} onClick={()=>setKbStatusFilter(s)} style={{padding:"4px 10px",borderRadius:20,fontSize:10,fontWeight:700,fontFamily:FM,cursor:"pointer",background:kbStatusFilter===s?(s==="published"?C.gd:s==="draft"?C.yd:C.ad):"transparent",color:kbStatusFilter===s?(s==="published"?C.g:s==="draft"?C.y:C.a):C.t3,border:`1px solid ${kbStatusFilter===s?C.b2:C.b1}`,textTransform:"capitalize"}}>{s}</button>
          ))}
        </div>
        <div style={{background:C.s1,border:`1px solid ${C.b1}`,borderRadius:14,overflow:"hidden"}}>
          {filtered.map((a,i)=>(
            <div key={a.id} onClick={()=>{setViewArt(a);setArticles(p=>p.map(x=>x.id===a.id?{...x,views:x.views+1}:x));}} className="hov" style={{display:"flex",alignItems:"center",gap:14,padding:"14px 18px",borderBottom:i<filtered.length-1?`1px solid ${C.b1}`:"none",cursor:"pointer",transition:"background .12s"}}>
              <div style={{flex:1,minWidth:0}}>
                <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}>
                  <span style={{fontSize:14,fontWeight:600,color:C.t1}}>{a.title}</span>
                  <Tag text={a.status} color={a.status==="published"?C.g:C.y}/>
                </div>
                <div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}>
                  <span style={{fontSize:10,color:C.t3,fontFamily:FM}}>{KB_CATS.find(c=>c.id===a.cat)?.icon} {KB_CATS.find(c=>c.id===a.cat)?.name}</span>
                  <span style={{fontSize:10,color:C.t3}}>·</span>
                  <span style={{fontSize:10,color:C.t3,fontFamily:FM}}>{a.updated}</span>
                  {(a.tags||[]).slice(0,3).map(tag=><span key={tag} style={{fontSize:9,color:C.cy,fontFamily:FM,background:C.cy+"10",padding:"1px 6px",borderRadius:10}}>#{tag}</span>)}
                </div>
              </div>
              <div style={{display:"flex",gap:12,alignItems:"center",flexShrink:0}}>
                <div style={{textAlign:"center",minWidth:40}}><div style={{fontSize:8,color:C.t3,fontFamily:FM}}>VIEWS</div><div style={{fontSize:13,fontWeight:700,fontFamily:FM,color:C.a}}>{a.views}</div></div>
                <div style={{textAlign:"center",minWidth:40}}><div style={{fontSize:8,color:C.t3,fontFamily:FM}}>HELPFUL</div><div style={{fontSize:13,fontWeight:700,fontFamily:FM,color:a.helpful>=85?C.g:a.helpful>=70?C.y:C.r}}>{a.helpful}%</div></div>
              </div>
              <div style={{display:"flex",gap:3}} onClick={e=>e.stopPropagation()}>
                <button onClick={()=>{setEditArt(a);setArtTitle(a.title);setArtBody(a.body);setArtCat(a.cat);setArtStatus(a.status);setArtTags((a.tags||[]).join(", "));setShowEditor(true);}} style={{width:26,height:26,borderRadius:6,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,background:C.s3,border:`1px solid ${C.b1}`,cursor:"pointer",color:C.t3}} className="hov">✎</button>
                <button onClick={()=>{setArticles(p=>p.filter(x=>x.id!==a.id));showT("Article deleted","success");}} style={{width:26,height:26,borderRadius:6,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,background:C.rd,border:`1px solid ${C.r}44`,cursor:"pointer",color:C.r}}>✕</button>
              </div>
            </div>
          ))}
          {filtered.length===0&&<EmptyState icon="📄" title="No articles found" desc="Try different search terms or category filters, or create a new article." action="+ New Article" onAction={()=>{setEditArt(null);setArtTitle("");setArtBody("");setShowEditor(true);}}/>}
        </div>
      </>}

      {/* ═══ CATEGORIES ═══ */}
      {kbTab==="categories"&&<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>
        {KB_CATS.map(cat=>{const arts=articles.filter(a=>a.cat===cat.id);const pub=arts.filter(a=>a.status==="published").length;const totalViews=arts.reduce((s,a)=>s+a.views,0);return(
          <div key={cat.id} onClick={()=>{setKbCatFilter(cat.id);setKbTab("articles");}} className="hov" style={{background:C.s1,border:`1px solid ${C.b1}`,borderRadius:14,padding:"18px",cursor:"pointer",transition:"background .12s"}}>
            <div style={{fontSize:32,marginBottom:10}}>{cat.icon}</div>
            <div style={{fontSize:15,fontWeight:700,fontFamily:FD,marginBottom:2}}>{cat.name}</div>
            <div style={{fontSize:11,color:C.t3,marginBottom:12}}>{cat.desc}</div>
            <div style={{display:"flex",gap:12,marginBottom:10}}>
              <div><div style={{fontSize:8,color:C.t3,fontFamily:FM}}>ARTICLES</div><div style={{fontSize:14,fontWeight:800,fontFamily:FM,color:C.a}}>{arts.length}</div></div>
              <div><div style={{fontSize:8,color:C.t3,fontFamily:FM}}>PUBLISHED</div><div style={{fontSize:14,fontWeight:800,fontFamily:FM,color:C.g}}>{pub}</div></div>
              <div><div style={{fontSize:8,color:C.t3,fontFamily:FM}}>VIEWS</div><div style={{fontSize:14,fontWeight:800,fontFamily:FM,color:C.cy}}>{totalViews}</div></div>
            </div>
            <div style={{height:5,background:C.bg,borderRadius:3,overflow:"hidden"}}><div style={{width:(pub/Math.max(arts.length,1)*100)+"%",height:"100%",background:C.g,borderRadius:3}}/></div>
          </div>
        );})}
      </div>}

      {/* ═══ ANALYTICS ═══ */}
      {kbTab==="analytics"&&<>
        <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:10,marginBottom:20}}>
          {[{l:"Total Articles",v:articles.length,c:C.a},{l:"Published",v:articles.filter(a=>a.status==="published").length,c:C.g},{l:"Drafts",v:articles.filter(a=>a.status==="draft").length,c:C.y},{l:"Total Views",v:articles.reduce((s,a)=>s+a.views,0).toLocaleString(),c:C.cy},{l:"Avg Helpful",v:Math.round(articles.filter(a=>a.helpful).reduce((s,a)=>s+a.helpful,0)/Math.max(articles.filter(a=>a.helpful).length,1))+"%",c:C.p}].map(k=>(
            <div key={k.l} style={{background:C.s1,border:`1px solid ${C.b1}`,borderRadius:12,padding:"14px"}}>
              <div style={{fontSize:9,color:C.t3,fontFamily:FM,marginBottom:4}}>{k.l}</div>
              <div style={{fontSize:24,fontWeight:800,fontFamily:FD,color:k.c}}>{k.v}</div>
            </div>
          ))}
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:C.s1,border:`1px solid ${C.b1}`,borderRadius:14,overflow:"hidden"}}>
            <div style={{padding:"14px 18px",borderBottom:`1px solid ${C.b1}`}}><span style={{fontSize:14,fontWeight:700,fontFamily:FD}}>Top Articles by Views</span></div>
            {[...articles].sort((a,b)=>b.views-a.views).slice(0,8).map((a,i)=>(
              <div key={a.id} onClick={()=>{setViewArt(a);}} className="hov" style={{display:"flex",alignItems:"center",gap:10,padding:"10px 18px",borderBottom:`1px solid ${C.b1}`,cursor:"pointer"}}>
                <span style={{fontSize:13,fontWeight:800,fontFamily:FD,color:i<3?C.a:C.t3,width:20}}>{i+1}</span>
                <div style={{flex:1}}><div style={{fontSize:12,fontWeight:600}}>{a.title}</div><div style={{fontSize:9,color:C.t3,fontFamily:FM}}>{KB_CATS.find(c=>c.id===a.cat)?.name}</div></div>
                <span style={{fontSize:12,fontWeight:700,fontFamily:FM,color:C.a}}>{a.views}</span>
              </div>
            ))}
          </div>
          <div style={{background:C.s1,border:`1px solid ${C.b1}`,borderRadius:14,overflow:"hidden"}}>
            <div style={{padding:"14px 18px",borderBottom:`1px solid ${C.b1}`}}><span style={{fontSize:14,fontWeight:700,fontFamily:FD}}>Coverage by Category</span></div>
            {KB_CATS.map(cat=>{const cnt=articles.filter(a=>a.cat===cat.id).length;return(
              <div key={cat.id} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 18px",borderBottom:`1px solid ${C.b1}`}}>
                <span style={{fontSize:16}}>{cat.icon}</span>
                <span style={{fontSize:12,color:C.t2,flex:1}}>{cat.name}</span>
                <div style={{width:80,height:6,background:C.bg,borderRadius:3}}><div style={{width:(cnt/Math.max(...KB_CATS.map(c=>articles.filter(a=>a.cat===c.id).length),1)*100)+"%",height:"100%",background:C.a,borderRadius:3}}/></div>
                <span style={{fontSize:11,fontWeight:700,fontFamily:FM,color:C.a,width:20,textAlign:"right"}}>{cnt}</span>
              </div>
            );})}
          </div>
        </div>
      </>}
      </>}
    </div>

    {/* ═══ EDITOR MODAL ═══ */}
    {showEditor&&<Mdl title={editArt?"Edit Article":"New Article"} onClose={()=>{setShowEditor(false);setEditArt(null);}} w={640}>
      <Fld label="Title"><Inp val={artTitle} set={setArtTitle} ph="Article title…"/></Fld>
      <div style={{display:"flex",gap:14}}>
        <div style={{flex:1}}><Fld label="Category"><Sel val={artCat} set={setArtCat} opts={KB_CATS.map(c=>({v:c.id,l:c.icon+" "+c.name}))}/></Fld></div>
        <div style={{flex:1}}><Fld label="Status"><Sel val={artStatus} set={setArtStatus} opts={[{v:"draft",l:"Draft"},{v:"published",l:"Published"}]}/></Fld></div>
      </div>
      <Fld label="Tags (comma-separated)"><Inp val={artTags} set={setArtTags} ph="e.g. setup, channels, whatsapp"/></Fld>
      <Fld label="Content">
        <div style={{display:"flex",justifyContent:"flex-end",marginBottom:6}}>
          <button onClick={genAIArticle} disabled={aiGenLoad} style={{padding:"4px 12px",borderRadius:6,fontSize:10,fontWeight:700,color:C.p,background:C.pd,border:`1px solid ${C.p}44`,cursor:"pointer",fontFamily:FM}}>{aiGenLoad?"✦ Generating…":"✦ AI Generate Article"}</button>
        </div>
        {/* Formatting toolbar */}
        <div style={{display:"flex",gap:2,padding:"6px 8px",background:C.s2,border:`1px solid ${C.b1}`,borderRadius:"8px 8px 0 0",borderBottom:"none",flexWrap:"wrap"}}>
          {[{l:"B",fn:()=>setArtBody(p=>p+"**bold**"),t:"Bold"},{l:"I",fn:()=>setArtBody(p=>p+"_italic_"),t:"Italic",s:true},{l:"H1",fn:()=>setArtBody(p=>p+"\n# Heading\n"),t:"Heading 1"},{l:"H2",fn:()=>setArtBody(p=>p+"\n## Subheading\n"),t:"Heading 2"},{l:"—",fn:()=>setArtBody(p=>p+"\n---\n"),t:"Divider"},{l:"•",fn:()=>setArtBody(p=>p+"\n- List item\n"),t:"Bullet list"},{l:"1.",fn:()=>setArtBody(p=>p+"\n1. Step one\n"),t:"Numbered list"},{l:"</>",fn:()=>setArtBody(p=>p+"`code`"),t:"Inline code"},{l:"{ }",fn:()=>setArtBody(p=>p+"\n```\ncode block\n```\n"),t:"Code block"},{l:"🔗",fn:()=>setArtBody(p=>p+"[Link text](https://url)"),t:"Link"},{l:"📷",fn:()=>setArtBody(p=>p+"\n![Alt text](image-url)\n"),t:"Image"},{l:"📎",fn:()=>setArtBody(p=>p+"\n> Blockquote\n"),t:"Quote"},{l:"📋",fn:()=>setArtBody(p=>p+"\n| Column 1 | Column 2 |\n| --- | --- |\n| Cell | Cell |\n"),t:"Table"}].map(b=>(
            <button key={b.l} onClick={b.fn} title={b.t} style={{padding:"3px 8px",borderRadius:4,fontSize:b.s?11:10,fontWeight:b.l==="B"?800:b.s?400:600,fontStyle:b.s?"italic":"normal",fontFamily:b.l==="</>"||b.l==="{ }"?FM:FB,color:C.t2,background:"transparent",border:`1px solid transparent`,cursor:"pointer"}} className="hov">{b.l}</button>
          ))}
          <div style={{flex:1}}/>
          <button onClick={async()=>{showT("AI generating article…","info");try{const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:800,system:"You are a technical writer. Write a clear, structured KB article. Use # for headings, - for bullets, 1. for steps. No markdown fences. Be concise and practical.",messages:[{role:"user",content:"Write a help article titled: "+(artTitle||"How to get started")+" for category: "+artCat}]})});const d=await res.json();setArtBody(d.content?.[0]?.text||"");}catch(e){setArtBody("# "+artTitle+"\n\nThis article covers…\n\n## Getting Started\n\n1. Step one\n2. Step two\n\n## FAQ\n\n- Question: Answer\n");}}} style={{padding:"3px 10px",borderRadius:5,fontSize:9,fontWeight:700,color:C.p,background:C.pd,border:`1px solid ${C.p}44`,cursor:"pointer",fontFamily:FM}}>✦ AI Write</button>
        </div>
        <textarea value={artBody} onChange={e=>setArtBody(e.target.value)} rows={12} placeholder="Write your article content using markdown:\n# Heading\n## Subheading\n- Bullet point\n1. Numbered step\n**bold** _italic_ `code`\n[Link](url) ![Image](url)" style={{width:"100%",background:C.bg,border:`1px solid ${C.b1}`,borderRadius:"0 0 8px 8px",padding:"12px",fontSize:13,color:C.t1,fontFamily:FM,resize:"vertical",outline:"none",lineHeight:1.7,boxSizing:"border-box"}}/>
        <div style={{fontSize:10,color:C.t3,fontFamily:FM,marginTop:4}}>{artBody.length} characters · {artBody.split("\n").filter(l=>l===l.toUpperCase()&&l.length>3&&l.length<60).length} sections</div>
      </Fld>
      <div style={{display:"flex",gap:10,justifyContent:"flex-end"}}><Btn ch="Cancel" v="ghost" onClick={()=>{setShowEditor(false);setEditArt(null);}}/><Btn ch={editArt?"Save Changes":"Create Article"} v="primary" onClick={saveArt}/></div>
    </Mdl>}
  </div>;
}


